import { HEADQUARTERS, STAFF, STATUS_OPTS } from "./data.js";

// STAGE_DEFS — pages-stages.jsx StageRegister 컴포넌트가 참조하는 단계별 정의(V3.05 근거)
export const STAGE_DEFS = {
  stage1: {
    no: 1,
    key: "stage1",
    title: "제안품의",
    persona: "사업부 기안자",
    prevLabel: null,
    nextLabel: "수행품의 (대기)",
    next2Label: "구매품의 (대기)",
    fields: [
      { key: "bizInfo", label: "사업정보 등록", type: "ox", required: true },
      { key: "hq", label: "요청본부", type: "combo", options: HEADQUARTERS, required: true },
      { key: "requester", label: "요청자 (담당 프로명)", type: "combo", options: STAFF, required: true },
      { key: "vrb1", label: "전사VRB1", type: "date", note: "산출일 -10" },
      { key: "vrb2", label: "전사VRB2(본부VRB)", type: "date", note: "산출일 -3" },
      { key: "proposal", label: "제안품의 (구 사업품의)", type: "date", note: "산출일 -1" },
    ],
    baseline: { key: "submitDate", label: "제안제출일 · 스텝1 기준일(F열)", note: "D-10/D-3/D-1 산출 기준", required: true },
    outputs: [
      { label: "산출일 VRB1", note: "= 제안제출일 -10일", days: -10 },
      { label: "산출일 VRB2", note: "= 제안제출일 -3일", days: -3 },
      { label: "산출일 제안품의", note: "= 제안제출일 -1일", days: -1 },
    ],
    extraFields: [
      { key: "customer", label: "매출처", type: "text" },
      { key: "bizType", label: "사업유형(SI/ASP)", type: "combo", options: ["SI", "ASP"] },
      { key: "bizName", label: "사업명", type: "text" },
      { key: "periodStart", label: "계약기간 시작(월단위 가집계)", type: "date" },
      { key: "periodEnd", label: "계약기간 종료(월단위 가집계)", type: "date" },
      { key: "amountSale", label: "제안금액 - 매출", type: "number" },
      { key: "amountBuy", label: "제안금액 - 매입", type: "number" },
    ],
    erpNote: "ERP: VRB자료(사업정보·소속·VRB) 직접 연동 가능",
  },
  stage2: {
    no: 2,
    key: "stage2",
    title: "수행품의",
    persona: "구매계약팀 담당자",
    prevLabel: "제안품의",
    nextLabel: null,
    next2Label: "구매품의 (대기)",
    fields: [
      { key: "contractInfo", label: "계약정보 등록", type: "ox", required: true },
      { key: "owner", label: "담당자 (구매계약팀)", type: "combo", options: STAFF, required: true },
      { key: "vrb3", label: "VRB3", type: "date", note: "계약기간 확정 후 항목" },
      { key: "quoteDate", label: "견적제출일", type: "date", note: "산출일 -7" },
      { key: "issueDate", label: "이슈검토", type: "date", note: "산출일 -7" },
      { key: "progress", label: "진행상황", type: "combo", options: STATUS_OPTS, required: true },
    ],
    baseline: { key: "approvalDate", label: "수행품의/매출계약 품의(결재완료) · 스텝2 기준일(U열)", note: "구 수행손익품의", required: true },
    outputs: [
      { label: "산출일 VRB3·견적·이슈검토", note: "= 기준일 -7일", days: -7 },
      { label: "산출일 수행품의", note: "= 기준일 -5일", days: -5 },
    ],
    purchaseOnlyFields: [
      { key: "conflict", label: "이해 상충 여부", type: "combo", options: ["정상", "이해상충"] },
      { key: "negotiated", label: "수의계약 여부", type: "combo", options: ["경쟁계약", "수의계약"] },
      { key: "costSaving", label: "원가 절감액 (산출)", type: "readonly-number", note: "사전 - 수행 자동 산출 (산식 미확정 O-10)" },
    ],
    extraFields: [
      { key: "periodStartConfirm", label: "계약기간 시작 확정 (일단위)", type: "date" },
      { key: "periodEndConfirm", label: "계약기간 종료 확정 (일단위)", type: "date" },
      { key: "finalContractDate", label: "매출 최종 계약일자 (오프라인)", type: "date" },
      { key: "approval1", label: "1차 결재일", type: "date" },
      { key: "approval2", label: "2차 결재일", type: "date" },
      { key: "approval3", label: "3차 결재일", type: "date" },
      { key: "orderAmountSale", label: "수주금액 - 매출", type: "number" },
      { key: "orderAmountBuy", label: "수주금액 - 매입", type: "number" },
      { key: "priceNegotiated", label: "단가 협상여부", type: "combo", options: ["협상함", "협상안함"] },
      { key: "priceSaving", label: "단가 협상 절감액", type: "number" },
    ],
    erpNote: "ERP: 수행품의 이전 등록현황 API 연동",
  },
  stage3: {
    no: 3,
    key: "stage3",
    title: "구매품의",
    persona: "구매계약팀 담당자",
    prevLabel: "수행품의",
    nextLabel: null,
    next2Label: null,
    fields: [
      { key: "purchaseInfo", label: "매입계약 정보 등록", type: "ox", required: true },
      { key: "owner", label: "담당자", type: "combo", options: STAFF, required: true },
      { key: "issueDate", label: "이슈검토", type: "date", note: "산출일 -1" },
      { key: "progress", label: "진행상황", type: "combo", options: STATUS_OPTS, required: true },
      { key: "purchaseApproval", label: "매입품의 (결재완료)", type: "date", note: "구 매입계약품의 · 산출일 -1" },
      { key: "completeSale", label: "계약완료예정 - 매출", type: "date" },
      { key: "startSale", label: "계약시작일 - 매출", type: "date" },
    ],
    baseline: { key: "startBuy", label: "계약시작일 - 매입 · 기준일 D-3 산정 원천", note: "N건 시 MIN(매입계약 시작일) -3일", required: true },
    outputs: [
      { label: "산출일 이슈검토·매입품의", note: "= 기준일 -1일", days: -1 },
      { label: "산출일 계약완료예정(매입)", note: "= 기준일 -3일", days: -3 },
    ],
    purchaseOnlyFields: [
      { key: "conflict", label: "이해 상충 여부", type: "combo", options: ["정상", "이해상충"] },
      { key: "negotiated", label: "수의계약 여부", type: "combo", options: ["경쟁계약", "수의계약"] },
      { key: "costSaving", label: "원가 절감액 (산출)", type: "readonly-number", note: "사전 - 수행 자동 산출 (산식 미확정 O-10)" },
    ],
    manualClosureFields: [
      { key: "electronic", label: "전자계약 여부", type: "ox" },
      { key: "sent", label: "계약서 발송 (수의/교부/우편)", type: "ox" },
      { key: "received", label: "계약서 회신 (서명본 수령)", type: "ox" },
      { key: "insurance", label: "보험 발행 (이행/하자보증 증권)", type: "ox" },
    ],
    extraFields: [
      { key: "completeBuy", label: "계약완료예정 - 매입", type: "date" },
      { key: "conflictPartner", label: "이해상충 협력사명", type: "text" },
      { key: "outsourceSaving", label: "외주 도입 절감액", type: "number" },
    ],
    repeater: {
      label: "매입계약 1~N (매입처별 반복, FR-16)",
      itemFields: [
        { key: "partner", label: "매입처", type: "text" },
        { key: "periodStart", label: "계약기간 시작", type: "date" },
        { key: "periodEnd", label: "계약기간 종료", type: "date" },
        { key: "amount", label: "계약금액", type: "number" },
        { key: "priceSaving", label: "단가 절감액", type: "number" },
      ],
    },
    erpNote: "ERP: 외주계약 Z20625 (IF-PS-001) 직접 매핑",
  },
};
